{
 "title": "Electricity Usage",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Peak Current in Time Period (A)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(electricity_current_milliamps[$__interval])/1000"
    }
   ]
  },
  {
   "title": "Latest Current (A)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "electricity_current_milliamps / 1000"
    }
   ]
  },
  {
   "title": "Electricity Usage - Amps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "electricity_current_milliamps / 1000"
    }
   ]
  },
  {
   "title": "Peak Power in Time Period (kW)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max_over_time(electricity_current_watts[$__interval])/1000"
    }
   ]
  },
  {
   "title": "Latest Power (kW)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "electricity_current_watts / 1000"
    }
   ]
  },
  {
   "title": "Electricity usage - Watts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    { "expr": "electricity_current_watts" }
   ]
  }
 ]
}