version: '3.7'

services:

  zookeeper:
    image: strimzi/kafka:0.19.0-kafka-2.5.0
    command: [
      "sh", "-c",
      "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    ports:
      - "2181:2181"
    environment:
      LOG_DIR: /tmp/logs

  kafka:
    image: strimzi/kafka:0.19.0-kafka-2.5.0
    command: [
      "sh", "-c",
      "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
    ]
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.82:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181


  prom:
    container_name: prometheus
    image: prom/prometheus
    command:
      - "--config.file=/config/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - "9090:9090"
    user: "1000:1000"
    volumes:
      - './config:/config'
      - './target/data/prometheus:/prometheus'

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prom
    environment:
      - GF_PATHS_CONFIG=/config/grafana.ini
    user: "1000:1000"
    volumes:
      - './config:/config'
      - './target/data/grafana:/var/lib/grafana'
      - './target/logs/grafana:/var/log/grafana'

  quarkus-micrometer:
    container_name: electricity-monitor
    image: johara/controller:1.0.0-SNAPSHOT
    ports:
      - "8281:8080"
    depends_on:
      - zookeeper
